params {
    input = '{{ input }}'
    schema_path = '{{ schema_path }}'
    ptf = '{{ ptf }}'
    threads = {{ chewie_threads }}
    force = {{ force }} 
    profile_pass = {{ filter_threshold }}
    cluster = {{ cluster }}
    thresholds = '{{ cluster_threshold }}'

}